### ISSUE TITLE
fix saucelabs integration

### ISSUE THREAD

**Issue by hitz** [ENCODE-DCC/snovault#1]
Browser tests fail on travis-ci, should just be a matter of creating encrypted keys and putting them in travis-ci.yml?

**Comment by kilodalton** [comment]
Create an Open Sauce account on Sauce Labs for this repo:
 - https://saucelabs.com/opensauce/
 
 

Get Sauce Lab access key:
 - https://saucelabs.com/beta/user-settings


Directions to add and encrypt Sauce Credentials:
 - how to add Sauce creds: https://docs.travis-ci.com/user/sauce-connect/

 - encrypt `SAUCE_USERNAME` and `SAUCE_ACCESS_KEY`: 

  https://docs.travis-ci.com/user/encryption-keys/

 - add the line with the secure credentials  to the `.travis.yml`

**Comment by hitz** [comment]
I think we either have to pay for more sub-accounts, or make another saucelabs account on a different email

**Comment by hitz** [comment]
fixed in #5.  I made a new saucelabs account "ciscohitz" which goes to my gmail.
