### ISSUE TITLE
can't submit tissue biosample 

### ISSUE THREAD

**Issue by nathankw** [ENCODE-DCC/snovault#101]
Hi,
I'm trying to submit a biosample with biosample_type=tissue, but get this error:
```
    {
      "description": "'tissue' is not one of ['single cell', 'primary cell', 'cell line', 'in vitro differentiated cells', 'stem cell', 'induced pluripotent stem cell line']",
      "location": "body",
      "name": [
        "biosample_type"
      ]
    }

```

yet the biosample profile includes "tissue":

```
"biosample_type": {
"type": "string",
"description": "The general category of the biosample.",
"enum": [
"single cell",
"cell line",
"in vitro differentiated cells",
"induced pluripotent stem cell line",
"primary cell",
"stem cell",
"tissue",
"whole organisms"
],
"comment": "Required property. The specified category should match the type of ontology used to describe the biosample.",
"title": "Biosample type"
},
```

**Comment by gabdank** [comment]
it depends on the biosample information you are trying to submit. for instance, if you specify the "phase" property you can not use "tissue" biosample_type. That is what this message trying to say - that some property you specified limits the biosample_type to the list of:
 ['single cell', 'primary cell', 'cell line', 'in vitro differentiated cells', 'stem cell', 'induced pluripotent stem cell line']

**Comment by nathankw** [comment]
Thanks, yeah I was submitting culture_harvest_data instead of date_obtained.
