### ISSUE TITLE
travis to auto push new version to pypi?

### ISSUE THREAD

**Issue by j1z0** [ENCODE-DCC/snovault#11]
@hitz - would it be feasible / reasonable to have travis auto push to pypi on successful master builds in the master repo?  Would make it easier to always get the latest and greatest of snovault.

Here's the docs on doing that:

https://docs.travis-ci.com/user/deployment/pypi

**Comment by hitz** [comment]
I'll see what I can do.   What I did for encoded (literally last night) was to do the following in buildout.cfg:

auto-checkout = snovault
and then add
snovault = git https://github.com/ENCODE-DCC/snovault.git branch=update_snovault

to [sources] stanza.

This is probably best if people are actually developing snovault.   It should also be branch_master, but I was wrestling with some dumb saucelabs BDD test descrepancy and didn't want to merge it to master.

Also - that branch update_snovault - has a few updates from encoded.

**Comment by j1z0** [comment]
ahh yeah I was considering something similar in setup.py…. will do that for now.

thanks.
