### ISSUE TITLE
make into PyPi package

### ISSUE THREAD

**Issue by hitz** [ENCODE-DCC/snovault#2]

**Comment by hitz** [comment]
This is in branch distro.  It doesn't work.   For some reason, when I pip install it doesn't install the required packages.

>Collecting snovault
  Using cached https://testpypi.python.org/packages/11/02/b9cc5cb6a1fa28e24cf0e1bb87e19e202333175f879d654f994b2fe86044/snovault-0.13.tar.gz
Collecting Pillow (from snovault)
  Could not find a version that satisfies the requirement Pillow (from snovault) (from versions: )
No matching distribution found for Pillow (from snovault)

If you install Pillow (for example pip3 install python-pptx), I get the same error on the next package (PyBrowserID)

**Comment by hitz** [comment]
OH, I think the problem is that not all these packages are in testpypi!

**Comment by hitz** [comment]
Works! you can pip install snovault!

**Comment by kilodalton** [comment]
Nice work, @hitz !!!

**Comment by hitz** [comment]
There are versions 0.1 - 0.13 they are all functionally identical, I just didn't know you needed to delete them from build...

Trying to get these minor changes to build on travis, I might have to take out the snowflakes test database

**Comment by hitz** [comment]
fixed in #5
