### ISSUE TITLE
have mpindexer clean up

### ISSUE THREAD

**Issue by hitz** [ENCODE-DCC/snovault#32]
this isn't a real fix, but mpindexer leaks memory.

@tdreszer has a fix that sets  maxtaskperchild =4 and it seems to clean up much better after long indexes, although it still might leak a bit.

https://docs.python.org/2/library/multiprocessing.html

**Comment by hitz** [comment]
The parameters of chunksize=32 and maxtaskperchild=4 have not been optimized; this will probably be another ticket in encoded.

**Comment by tdreszer** [comment]
Ben I think we should use chunksize = 1024, maxtasks = 1 and a bit of logic in mpindexer.update_objects() to lower chunkiness as appropriate:
        uuid_count = len(uuids)
        chunkiness = int((uuid_count - 1) / self.processes) + 1
        if chunkiness > self.chunksize:
            chunkiness = self.chunksize

I have been running this in a demo.

**Comment by hitz** [comment]
can you make a snovault pull request?

**Comment by hitz** [comment]
Closed by https://github.com/ENCODE-DCC/snovault/pull/37
